-- Central schema, indexes, procedures, triggers, seed (central_db)

CREATE TABLE department (
  department_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE branch (
  branch_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  address TEXT NOT NULL
);

CREATE TABLE supplier (
  supplier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL UNIQUE
);

CREATE TABLE staff_central (
  staff_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  department_id INT NOT NULL,
  CONSTRAINT fk_staff_central_department
    FOREIGN KEY (department_id)
    REFERENCES department(department_id)
    ON DELETE RESTRICT
);

CREATE TABLE supplier_branch (
  supplier_id INT NOT NULL,
  branch_id INT NOT NULL,
  PRIMARY KEY (supplier_id, branch_id),
  CONSTRAINT fk_supplier_branch_supplier
    FOREIGN KEY (supplier_id)
    REFERENCES supplier(supplier_id)
    ON DELETE CASCADE,
  CONSTRAINT fk_supplier_branch_branch
    FOREIGN KEY (branch_id)
    REFERENCES branch(branch_id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_branch_name ON branch(name);
CREATE INDEX IF NOT EXISTS idx_department_name ON department(name);
CREATE INDEX IF NOT EXISTS idx_supplier_company_name ON supplier(company_name);
CREATE INDEX IF NOT EXISTS idx_staff_central_department_id ON staff_central(department_id);
CREATE INDEX IF NOT EXISTS idx_supplier_branch_supplier_id ON supplier_branch(supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_branch_branch_id ON supplier_branch(branch_id);

CREATE OR REPLACE FUNCTION trg_department_name_not_blank()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.name = btrim(NEW.name);
  IF NEW.name = '' THEN
    RAISE EXCEPTION 'department.name must not be empty';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER check_department_name
BEFORE INSERT OR UPDATE ON department
FOR EACH ROW
EXECUTE FUNCTION trg_department_name_not_blank();

CREATE OR REPLACE FUNCTION trg_branch_fields_not_blank()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.name = btrim(NEW.name);
  NEW.address = btrim(NEW.address);
  IF NEW.name = '' THEN
    RAISE EXCEPTION 'branch.name must not be empty';
  END IF;
  IF NEW.address = '' THEN
    RAISE EXCEPTION 'branch.address must not be empty';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER check_branch_fields
BEFORE INSERT OR UPDATE ON branch
FOR EACH ROW
EXECUTE FUNCTION trg_branch_fields_not_blank();

CREATE OR REPLACE FUNCTION trg_supplier_company_not_blank()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.company_name = btrim(NEW.company_name);
  IF NEW.company_name = '' THEN
    RAISE EXCEPTION 'supplier.company_name must not be empty';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER check_supplier_company
BEFORE INSERT OR UPDATE ON supplier
FOR EACH ROW
EXECUTE FUNCTION trg_supplier_company_not_blank();

CREATE OR REPLACE PROCEDURE sp_add_branch(p_name TEXT, p_address TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO branch (name, address) VALUES (p_name, p_address);
END;
$$;

CREATE OR REPLACE PROCEDURE sp_update_branch(p_branch_id INT, p_name TEXT, p_address TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE branch
  SET name = p_name,
      address = p_address
  WHERE branch_id = p_branch_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_delete_branch(p_branch_id INT)
LANGUAGE plpgsql
AS $$
BEGIN
  DELETE FROM branch WHERE branch_id = p_branch_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_add_supplier(p_company_name TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO supplier (company_name) VALUES (p_company_name);
END;
$$;

CREATE OR REPLACE PROCEDURE sp_add_department(p_name TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO department (name) VALUES (p_name);
END;
$$;

INSERT INTO branch (name, address) VALUES
  ('branch1', 'г. Новосибирск, ул. Ленина, 10'),
  ('branch2', 'г. Новосибирск, пр. Красный, 25');

INSERT INTO department (name) VALUES
  ('Закупки'),
  ('Финансы');

INSERT INTO staff_central (name, department_id)
SELECT 'Алиса Центр', d.department_id
FROM department d
WHERE d.name = 'Закупки';

INSERT INTO staff_central (name, department_id)
SELECT 'Борис Центр', d.department_id
FROM department d
WHERE d.name = 'Финансы';

INSERT INTO supplier (company_name) VALUES
  ('Ткани и белье ООО'),
  ('Продукты и сервис ООО');

-- Ткани и белье -> оба филиала
INSERT INTO supplier_branch (supplier_id, branch_id)
SELECT s.supplier_id, b.branch_id
FROM supplier s
JOIN branch b ON b.name IN ('branch1','branch2')
WHERE s.company_name = 'Ткани и белье ООО';

-- Продукты и сервис -> только branch1
INSERT INTO supplier_branch (supplier_id, branch_id)
SELECT s.supplier_id, b.branch_id
FROM supplier s
JOIN branch b ON b.name = 'branch1'
WHERE s.company_name = 'Продукты и сервис ООО';

-- Добавляем достаточно записей для требований
INSERT INTO supplier (company_name) VALUES
  ('ООО СеверСнаб'),
  ('АО СибирьФуд'),
  ('ООО ХоРеКа Сервис'),
  ('ООО ЛайнТекстиль'),
  ('ООО ЭкоБытХим'),
  ('ООО Мебель-Про'),
  ('ООО ТехноКухня'),
  ('ООО ПрофИнвентарь'),
  ('ООО СветЛюкс'),
  ('ООО КлиматСистемы'),
  ('ООО Прачечная Профи'),
  ('ООО КофеТрейд'),
  ('ООО БытСервис'),
  ('ООО Чистый Дом'),
  ('ООО Безопасность НСК');

WITH branch1 AS (
  SELECT branch_id AS id FROM branch WHERE name = 'branch1'
),
branch2 AS (
  SELECT branch_id AS id FROM branch WHERE name = 'branch2'
),
new_suppliers AS (
  SELECT supplier_id, row_number() OVER (ORDER BY supplier_id) AS rn
  FROM supplier
  WHERE company_name NOT IN ('Ткани и белье ООО', 'Продукты и сервис ООО')
)
INSERT INTO supplier_branch (supplier_id, branch_id)
SELECT ns.supplier_id,
       CASE
         WHEN ns.rn % 2 = 0 THEN (SELECT id FROM branch1)
         ELSE (SELECT id FROM branch2)
       END
FROM new_suppliers ns;
